### PR TITLE
Fix deduplication job

### LINKED ISSUE #12: Fix deduplication task
@medvedev1088  mentioned [here](https://github.com/blockchain-etl/hedera-etl/pull/6#discussion_r425035058) about limitations of UPDATE query.

Deduplication task as in won't work. It'll fail on step 2 where it tries to update rows with consensusTimestamp > lastValidTimestamp since the update job will span over streaming buffer.

Need to fix this.

### PR DESCRIPTION
**Pull request by apeksharma**
**Detailed description**:
- Fix the bug (#12)
- Redesign deduplication code
- Add full duplication (#13)

**Which issue(s) this PR fixes**:
Fixes #12 #13 

**Special notes for your reviewer**:
working on few kinks in test, will resolve them later. In meantime, please take a look. 
If everything looks good, i'll try to deploy it on test deployment tomorrow.

**Checklist**
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

File: hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/FullDeduplication.java [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+ */
+@Component
+public class FullDeduplication extends AbstractDeduplication {
+
+    public FullDeduplication(DedupeProperties properties, BigQuery bigQuery, MeterRegistry meterRegistry) {
+        super(DedupeType.FULL, properties, bigQuery, meterRegistry);
+    }
+
+    @Scheduled(fixedRateString = "${hedera.dedupe.fullFixedRate:86400000}") // default: 24 hr
+    public void run() {
```
Comment (medvedev1088) [inline hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/FullDeduplication.java:63]: In case there are bugs in the downstream libs e.g. in the BigQuery client, there is a risk that the task will get stuck (in case the downstream lib doesn't have timeouts when making network calls). I've faced this issue with PubSub lib for Python. Ideally we should be able to set timeouts for tasks, but unfortunately I couldn't find this possibility for @Scheduled. Will have to let it run for some time to see if this issue arises.

File: hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/IncrementalDeduplication.java [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+    private long probeEndTimestamp(long startTimestamp) throws InterruptedException {
+        long endTimestamp = startTimestamp;
+        long intervalInSec = incrementalProbeInteraval;
+        while (true) {
+            long nextEndTimestamp = startTimestamp + intervalInSec;
+            log.info("Probing for endTimestamp = {}", nextEndTimestamp);
+            try {
+                updateDedupeColumnTemplateQuery.inTimeWindow(startTimestamp, nextEndTimestamp);
+                log.info("successful");
+                Long latestUpdatedTimestamp = getLatestDedupeRowTemplateQuery.fromTimestamp(startTimestamp);
```
Comment (medvedev1088) [inline hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/IncrementalDeduplication.java]: I see that `getLatestDedupeRowTemplateQuery.fromTimestamp(...)` can return a null. It should be handled below.

File: hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/IncrementalDeduplication.java [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+
+    @Override
+    void saveState(TimestampWindow timestampWindow) throws InterruptedException {
+        setState.set(INCREMENTAL_LATEST_END_TIMESTAMP, String.valueOf(timestampWindow.getEndTimestamp()));
+    }
+
+    private long probeEndTimestamp(long startTimestamp) throws InterruptedException {
+        long endTimestamp = startTimestamp;
+        long intervalInSec = incrementalProbeInteraval;
+        while (true) {
```
Comment (medvedev1088) [inline hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/IncrementalDeduplication.java]: Might be a good idea to add iterations limit here to prevent infinite loop. An infinite loop is possible if we forgot to handle some edge case.

File: hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/AbstractDeduplication.java [hunk 4]
```diff
@@ -0,0 +1,150 @@
...
+    abstract TimestampWindow getTimestampWindow(Map<String, FieldValue> state) throws InterruptedException;
+
+    /** Implementations should override this to do all end-of-job state saving. */
+    abstract void saveState(TimestampWindow timestampWindow) throws InterruptedException;
+
+    public AbstractDeduplication(
+            DedupeType dedupeType, DedupeProperties properties, BigQuery bigQuery, MeterRegistry meterRegistry) {
+        String projectId = properties.getProjectId();
+        getDuplicates = new GetDuplicatesTemplateQuery(
+                projectId, DedupeType.INCREMENTAL, properties.getTransactionsTableFullName(), bigQuery, meterRegistry);
```
Comment (medvedev1088) [inline hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/AbstractDeduplication.java]: Should it be dedupeType instead of DedupeType.INCREMENTAL?

File: hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/IncrementalDeduplication.java [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+                // only cause the window to be smaller than what it could have been, but no correctness issues.
+                if (latestUpdatedTimestamp < nextEndTimestamp) {
+                    endTimestamp = latestUpdatedTimestamp;
+                    break;
+                } else {
+                    intervalInSec = 2 * intervalInSec; // quadratic probing, for faster catchup
+                }
+            } catch (BigQueryException e) {
+                log.info("failed");
+                endTimestamp = getLatestDedupeRowTemplateQuery.fromTimestamp(startTimestamp);
```
Comment (medvedev1088) [inline hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/IncrementalDeduplication.java]: Might cause NPE if getLatestDedupeRowTemplateQuery.fromTimestamp() returns null.

**Review by medvedev1088 — CHANGES_REQUESTED** [review]

File: hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/FullDeduplication.java (hunk 1 above)
Comment (apeksharma) [reply hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/FullDeduplication.java:63]: yes.
Similarly, setting timeout on individual jobs was something i was wondering initially, but deferred on it until after some experience has been gained here.

File: hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/IncrementalDeduplication.java (hunk 2 above)
Comment (apeksharma) [reply hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/IncrementalDeduplication.java]: done.

File: hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/IncrementalDeduplication.java (hunk 3 above)
Comment (apeksharma) [reply hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/IncrementalDeduplication.java]: done.

File: hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/IncrementalDeduplication.java (hunk 5 above)
Comment (apeksharma) [reply hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/IncrementalDeduplication.java]: code updated. shouldn't be possible now.

File: hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/AbstractDeduplication.java (hunk 4 above)
Comment (apeksharma) [reply hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/AbstractDeduplication.java]: ahh, thanks!

File: hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/FullDeduplication.java [hunk 6]
```diff
@@ -0,0 +1,78 @@
...
+ * Above assumption also incorporates in itself the fact that no duplicates should arrive as late as an hour.
+ * <p/>
+ * However, above assumption breaks down when the system is not functioning normally. To list some of the scenarios:
+ * <ul>
+ *   <li>If importer (publishing to pubsub) crashes. It can publish duplicates when it comes back up much later</li>
+ *   <li>If dataflow pipeline crashes due to a bug. It'll likely take more than an hour to fix it and restart
+ *   the pipeline.</li>
+ * </ul>
+ * To cover such scenarios, running an infrequent job which does deduplication over all past data is necessary.
+ */
```
Comment (medvedev1088) [inline hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/FullDeduplication.java:54]: Should also add a note here that there is a limit of 4000 partitions updated by a DML operation. That's more than 10 years of data, so we don't need to worry about it for now.

**Review by medvedev1088 — APPROVED** [review]

File: hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/FullDeduplication.java (hunk 6 above)
Comment (apeksharma) [reply hedera-deduplication-bigquery/src/main/java/com/hedera/dedupe/FullDeduplication.java:54]: done.
