### PR TITLE
Handing last couple items

### LINKED ISSUE #8: Add metric to dataflow to track transaction latency (now - consensusTimestamp)

### LINKED ISSUE #16: Debug the bigQueryInsertErrors
In the test run, 1 row insertion to BigQuery failed (of 24M rows so far).
Error:
```
{"errors":[{"debugInfo":"","location":"transaction.body.contractcreateinstance.memo","message":"Failed to decode bytes input. Byte fields must be base64 encoded.","reason":"invalid"}],"index":0}
```

Transaction
```
{
  "consensusTimestamp": 1568833603515197000,
  "entity": {
    "shardNum": 0,
    "realmNum": 0,
    "entityNum": 19416,
    "type": 2
  },
  "transactionType": 8,
  "transaction": {
    "body": {
      "transactionID": {
        "transactionValidStart": {
          "seconds": "1568833591",
          "nanos": 876370500
        },
        "accountID": {
          "shardNum": "0",
          "realmNum": "0",
          "accountNum": "13477"
        }
      },
      "nodeAccountID": {
        "shardNum": "0",
        "realmNum": "0",
        "accountNum": "3"
      },
      "transactionFee": "510139189",
      "transactionValidDuration": {
        "seconds": "30"
      },
      "generateRecord": true,
      "memo": "Test Contract tx-2",
      "contractCreateInstance": {
        "fileID": {
          "shardNum": "0",
          "realmNum": "0",
          "fileNum": "19415"
        },
        "gas": "250000",
        "initialBalance": "0",
        "proxyAccountID": {
          "shardNum": "0",
          "realmNum": "0",
          "accountNum": "0"
        },
        "autoRenewPeriod": {
          "seconds": "7890000"
        },
        "constructorParameters": "",
        "memo": "Test Contract-2"
      }
    },
    "sigMap": {
      "sigPair": [
        {
          "pubKeyPrefix": "",
          "ed25519": "e1hx4GTuf05gBBYn/kLOL/iQPSdNk189i9lDln9WwiYanbDVHDw0XjTkvbEWtLOeKy0uOvC/GtvOK5qfQmrRBQ=="
        }
      ]
    }
  },
  "transactionRecord": {
    "receipt": {
      "status": "SUCCESS",
      "contractID": {
        "shardNum": "0",
        "realmNum": "0",
        "contractNum": "19416"
      },
      "exchangeRate": {
        "currentRate": {
          "hbarEquiv": 30000,
          "centEquiv": 320235,
          "expirationTime": {
            "seconds": "1568768400"
          }
        },
        "nextRate": {
          "hbarEquiv": 30000,
          "centEquiv": 298800,
          "expirationTime": {
            "seconds": "1568772000"
          }
        }
      },
      "topicSequenceNumber": "0",
      "topicRunningHash": "",
      "topicRunningHashVersion": "0"
    },
    "transactionHash": "HK59cRMNMURRaXuPM6Niw3iMeOJEUGwopQHImsidNMS3HnlLgIsAls3SQREG82f2",
    "consensusTimestamp": {
      "seconds": "1568833603",
      "nanos": 515197000
    },
    "transactionID": {
      "transactionValidStart": {
        "seconds": "1568833591",
        "nanos": 876370500
      },
      "accountID": {
        "shardNum": "0",
        "realmNum": "0",
        "accountNum": "13477"
      }
    },
    "memo": "Test Contract tx-2",
    "transactionFee": "493596009",
    "contractCreateResult": {
      "contractID": {
        "shardNum": "0",
        "realmNum": "0",
        "contractNum": "19416"
      },
      "contractCallResult": "",
      "errorMessage": "",
      "bloom": "",
      "gasUsed": "96",
      "logInfo": [
        
      ],
      "createdContractIDs": [
        
      ]
    },
    "transferList": {
      "accountAmounts": [
        {
          "accountID": {
            "shardNum": "0",
            "realmNum": "0",
            "accountNum": "13477"
          },
          "amount": "-486655787"
        },
        {
          "accountID": {
            "shardNum": "0",
            "realmNum": "0",
            "accountNum": "3"
          },
          "amount": "10320881"
        },
        {
          "accountID": {
            "shardNum": "0",
            "realmNum": "0",
            "accountNum": "98"
          },
          "amount": "476334906"
        },
        {
          "accountID": {
            "shardNum": "0",
            "realmNum": "0",
            "accountNum": "13477"
          },
          "amount": "-6940222"
        },
        {
          "accountID": {
            "shardNum": "0",
            "realmNum": "0",
            "accountNum": "98"
          },
          "amount": "6940222"
        },
        {
          "accountID": {
            "shardNum": "0",
            "realmNum": "0",
            "accountNum": "13477"
          },
          "amount": "-75648"
        },
        {
          "accountID": {
            "shardNum": "0",
            "realmNum": "0",
            "accountNum": "98"
          },
          "amount": "75648"
        }
      ]
    }
  },
  "nonFeeTransfers": [
    {
      "accountID": {
        "shardNum": "0",
        "realmNum": "0",
        "accountNum": "13477"
      },
      "amount": "0"
    },
    {
      "accountID": {
        "shardNum": "0",
        "realmNum": "0",
        "accountNum": "19416"
      },
      "amount": "0"
    }
  ],
  "consensusTimestampTruncated": "2019-09-18T19:06:43.515197Z"
}
```

### LINKED ISSUE #17: Add table for transactionType
Add table containing mapping from transactionType id to transactionType name.
```
mirror_node=# select * from t_transaction_types ;
 proto_id |          name
----------+------------------------
       23 | FREEZE
       14 | CRYPTOTRANSFER
       15 | CRYPTOUPDATEACCOUNT
       12 | CRYPTODELETE
        7 | CONTRACTCALL
        8 | CONTRACTCREATEINSTANCE
        9 | CONTRACTUPDATEINSTANCE
       17 | FILECREATE
       16 | FILEAPPEND
       19 | FILEUPDATE
       18 | FILEDELETE
       11 | CRYPTOCREATEACCOUNT
       20 | SYSTEMDELETE
       21 | SYSTEMUNDELETE
       22 | CONTRACTDELETEINSTANCE
       24 | CONSENSUSCREATETOPIC
       25 | CONSENSUSUPDATETOPIC
       26 | CONSENSUSDELETETOPIC
       27 | CONSENSUSSUBMITMESSAGE
       10 | CRYPTOADDLIVEHASH
       13 | CRYPTODELETELIVEHASH
```

### PR DESCRIPTION
**Pull request by apeksharma**
**Detailed description**:
- Scripts to make dedupe deployment easier
- Fix bug in schema which resulted in the failed insert (#16)
- Added metric to dataflow job to track ingestionDelay from consensusTimestamp (#6)
- Add transaction_types table (#17)
- consistent naming of schema files
- Keep all schema files together. Move to a better location in future.
    
**Which issue(s) this PR fixes**:
Fixes #8 
Fixes #16
Fixes #17 

**Special notes for your reviewer**:
Diffs are nicely separated by commits. Was feeling lazy to send out 3 different PRs at 1:30am in night :)

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: scripts/create-tables.sh [hunk 1]
```diff
@@ -15,16 +15,50 @@ bq mk \
...
-  ${SCRIPT_DIR}/../hedera-dedupe-bigquery/state-schema.json
+  ${SCRIPT_DIR}/../hedera-etl-bigquery/src/main/resources/state-schema.json
+
+bq mk \
+  --table \
+  --description "Transaction Types" \
+  ${BQ_TRANSACTION_TYPES_TABLE} \
+  ${SCRIPT_DIR}/../hedera-etl-bigquery/src/main/resources/transaction-types-schema.json
+
+# Not using 'bq load' or 'bq insert' because of lack of flag to specify project_id. That'd require operator to
```
Comment (medvedev1088) [inline scripts/create-tables.sh]: `--project_id` is described in the global flags section https://cloud.google.com/bigquery/docs/reference/bq-cli-reference#bq_global_flags. I missed it at first too.

**Review by medvedev1088 — APPROVED** [review]

File: scripts/create-tables.sh (hunk 1 above)
Comment (apeksharma) [reply scripts/create-tables.sh]: ahh. removed the invalid comment.
Leaving query as is, no point spending time to change it.
